### ISSUE TITLE
FGDC metadata, step 2 (v1.6.9); UnicodeDecodeError

### ISSUE THREAD

**Issue by cgutierrez-01** [usgs/gems-tools-arcmap#80]
Hello! I have run into the following issue with the FGDC metadata, step 2 tool (v1.6.9).  The tool is failing when trying to the XML file for the DescriptionOfMapUnits table and is reporting a UnicodeDecodeError (see error message below). I have tried to remove any non-ASCII characters from the table but the issue persists. Any assistance with this issue will be greatly appreciated!

    Pruning unused srcinfo branches
    Replacing title and suppplinf
G:\CGS\GM_Work\Arcwork\Oakdale_100k\_GeMs_Oakdale_100k\Oakdale_100k__NAD27_UTM10\Oakdale_100k\workspace\EastHalfOakdale_100k.gdb
fileName=EastHalfOakdale_100k_DescriptionOfMapUnits-metadata.xml
    Writing XML to EastHalfOakdale_100k_DescriptionOfMapUnits-metadata.xml
Failed script MetadataFGDC-2...

Traceback (most recent call last):
  File "G:\CGS\GM_Work\Arcwork\ArcGIS_Files\GeMS\test\cg_testing\gems-tools-arcmap-master-v1.6.9\Scripts\GeMS_FGDC2_Arc10.py", line 503, in <module>
    fixObjXML(objName,objType,objLoc,domMR)
  File "G:\CGS\GM_Work\Arcwork\ArcGIS_Files\GeMS\test\cg_testing\gems-tools-arcmap-master-v1.6.9\Scripts\GeMS_FGDC2_Arc10.py", line 446, in fixObjXML
    writeDomToFile(wksp,dom,domName)
  File "G:\CGS\GM_Work\Arcwork\ArcGIS_Files\GeMS\test\cg_testing\gems-tools-arcmap-master-v1.6.9\Scripts\GeMS_FGDC2_Arc10.py", line 460, in writeDomToFile
    dom.writexml(out, encoding="utf-8")
  File "C:\Python27\ArcGIS10.7\Lib\xml\dom\minidom.py", line 1749, in writexml
    node.writexml(writer, indent, addindent, newl)
  File "C:\Python27\ArcGIS10.7\Lib\xml\dom\minidom.py", line 814, in writexml
    node.writexml(writer, indent+addindent, addindent, newl)
  File "C:\Python27\ArcGIS10.7\Lib\xml\dom\minidom.py", line 814, in writexml
    node.writexml(writer, indent+addindent, addindent, newl)
  File "C:\Python27\ArcGIS10.7\Lib\xml\dom\minidom.py", line 814, in writexml
    node.writexml(writer, indent+addindent, addindent, newl)
  File "C:\Python27\ArcGIS10.7\Lib\xml\dom\minidom.py", line 814, in writexml
    node.writexml(writer, indent+addindent, addindent, newl)
  File "C:\Python27\ArcGIS10.7\Lib\xml\dom\minidom.py", line 814, in writexml
    node.writexml(writer, indent+addindent, addindent, newl)
  File "C:\Python27\ArcGIS10.7\Lib\xml\dom\minidom.py", line 814, in writexml
    node.writexml(writer, indent+addindent, addindent, newl)
  File "C:\Python27\ArcGIS10.7\Lib\xml\dom\minidom.py", line 810, in writexml
    self.childNodes[0].writexml(writer, '', '', '')
  File "C:\Python27\ArcGIS10.7\Lib\xml\dom\minidom.py", line 1038, in writexml
    _write_data(writer, "%s%s%s" % (indent, self.data, newl))
  File "C:\Python27\ArcGIS10.7\Lib\xml\dom\minidom.py", line 298, in _write_data
    writer.write(data)
  File "C:\Python27\ArcGIS10.7\Lib\codecs.py", line 708, in write
    return self.writer.write(data)
  File "C:\Python27\ArcGIS10.7\Lib\codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)

Failed to execute (MetadataFGDC-2).
Failed at Wed Sep 29 11:53:03 2021 (Elapsed Time: 1 minutes 6 seconds)

**Comment by ethoms-usgs** [comment]
Try the toolbox in the branch I just pushed to the repo:

https://github.com/usgs/gems-tools-arcmap/tree/issue-80

and let me know.

**Comment by cgutierrez-01** [comment]
Thanks for the quick reply. I just tried the updated toolbox and it failed immediately on a syntax error in line 446:
    (wksp,dom,domName)writeDomToFile
I corrected the syntax error but the tool still fails, this time with a UnicodeEncodeError:

...  
DescriptionOfMapUnits
    Updating E-A stuff
      Field: OBJECTID
      Field: MapUnit
Failed script MetadataFGDC-2...

Traceback (most recent call last):
  File "G:\CGS\GM_Work\Arcwork\ArcGIS_Files\GeMS\test\cg_testing\gems-tools-arcmap-issue-80\Scripts\GeMS_FGDC2_Arc10.py", line 503, in <module>
    fixObjXML(objName,objType,objLoc,domMR)
  File "G:\CGS\GM_Work\Arcwork\ArcGIS_Files\GeMS\test\cg_testing\gems-tools-arcmap-issue-80\Scripts\GeMS_FGDC2_Arc10.py", line 433, in fixObjXML
    dom, dataSourceValues = updateTableDom(dom,objLoc,logFile)
  File "G:\CGS\GM_Work\Arcwork\ArcGIS_Files\GeMS\test\cg_testing\gems-tools-arcmap-issue-80\Scripts\GeMS_FGDC2_Arc10.py", line 383, in updateTableDom
    dom, dataSourceValues = __updateEntityAttributes(fc, fldNameList, dom, logFile)
  File "G:\CGS\GM_Work\Arcwork\ArcGIS_Files\GeMS\test\cg_testing\gems-tools-arcmap-issue-80\Scripts\GeMS_FGDC2_Arc10.py", line 200, in __updateEntityAttributes
    defs[t].append(row.FullName.decode('utf-8'))
  File "C:\Python27\ArcGIS10.7\Lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 21: ordinal not in range(128)

Failed to execute (MetadataFGDC-2).
Failed at Thu Sep 30 16:41:39 2021 (Elapsed Time: 25.35 seconds)

**Comment by ethoms-usgs** [comment]
Heck. Sorry about all this. I still do not quite understand encoding/decoding (and I didn't write this tool). 
I just pushed another version to that branch. If this doesn't work, I will dig deeper - or work to get the Python 3 version finished. 
Finally, I don't like the idea of excluding non-ASCII text from the unit names or descriptions, but it appears that the unicode character is a lower case accented e (é)  (https://www.compart.com/en/unicode/U+00E9). If it's acceptable, you could change that and see if it works.

**Comment by cgutierrez-01** [comment]
No need to apologize, Evan. I really appreciate all the work put into these tools and the assistance provided when they don't quite work as they should. I tried the latest version of the tool but it still complained about that character so, just to see if it would work, I changed the character to a standard e, and now the tool fails and complains about another character--0xe2--which apparently is an a with a caret (â).  This character does not exist in my DMU table so not sure what that is all about. Here's the full error message:

  DescriptionOfMapUnits
    Updating E-A stuff
      Field: OBJECTID
      Field: MapUnit
      Field: Name
      Field: FullName
      Field: Age
      Field: Description
      Field: HierarchyKey
      Field: ParagraphStyle
      Field: Label
      Field: Symbol
      Field: AreaFillRGB
      Field: AreaFillPatternDescription
      Field: DescriptionSourceID
      Field: GeoMaterial
      Field: GeoMaterialConfidence
      Field: DescriptionOfMapUnits_ID
    Pruning unused srcinfo branches
    Replacing title and suppplinf
    Writing XML to SanLuisObispo100kWest_DescriptionOfMapUnits-metadata.xml
Failed script MetadataFGDC-2...

Traceback (most recent call last):
  File "G:\CGS\GM_Work\Arcwork\ArcGIS_Files\GeMS\test\cg_testing\gems-tools-arcmap-issue-80\Scripts\GeMS_FGDC2_Arc10.py", line 503, in <module>
    fixObjXML(objName,objType,objLoc,domMR)
  File "G:\CGS\GM_Work\Arcwork\ArcGIS_Files\GeMS\test\cg_testing\gems-tools-arcmap-issue-80\Scripts\GeMS_FGDC2_Arc10.py", line 446, in fixObjXML
    writeDomToFile(wksp,dom,domName)
  File "G:\CGS\GM_Work\Arcwork\ArcGIS_Files\GeMS\test\cg_testing\gems-tools-arcmap-issue-80\Scripts\GeMS_FGDC2_Arc10.py", line 460, in writeDomToFile
    dom.writexml(out, encoding="utf-8")
  File "C:\Python27\ArcGIS10.7\Lib\xml\dom\minidom.py", line 1749, in writexml
    node.writexml(writer, indent, addindent, newl)
  File "C:\Python27\ArcGIS10.7\Lib\xml\dom\minidom.py", line 814, in writexml
    node.writexml(writer, indent+addindent, addindent, newl)
  File "C:\Python27\ArcGIS10.7\Lib\xml\dom\minidom.py", line 814, in writexml
    node.writexml(writer, indent+addindent, addindent, newl)
  File "C:\Python27\ArcGIS10.7\Lib\xml\dom\minidom.py", line 814, in writexml
    node.writexml(writer, indent+addindent, addindent, newl)
  File "C:\Python27\ArcGIS10.7\Lib\xml\dom\minidom.py", line 814, in writexml
    node.writexml(writer, indent+addindent, addindent, newl)
  File "C:\Python27\ArcGIS10.7\Lib\xml\dom\minidom.py", line 814, in writexml
    node.writexml(writer, indent+addindent, addindent, newl)
  File "C:\Python27\ArcGIS10.7\Lib\xml\dom\minidom.py", line 814, in writexml
    node.writexml(writer, indent+addindent, addindent, newl)
  File "C:\Python27\ArcGIS10.7\Lib\xml\dom\minidom.py", line 810, in writexml
    self.childNodes[0].writexml(writer, '', '', '')
  File "C:\Python27\ArcGIS10.7\Lib\xml\dom\minidom.py", line 1038, in writexml
    _write_data(writer, "%s%s%s" % (indent, self.data, newl))
  File "C:\Python27\ArcGIS10.7\Lib\xml\dom\minidom.py", line 298, in _write_data
    writer.write(data)
  File "C:\Python27\ArcGIS10.7\Lib\codecs.py", line 708, in write
    return self.writer.write(data)
  File "C:\Python27\ArcGIS10.7\Lib\codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 148: ordinal not in range(128)

Failed to execute (MetadataFGDC-2).
Failed at Thu Sep 30 20:49:48 2021 (Elapsed Time: 45.40 seconds)

**Comment by ethoms-usgs** [comment]
Carlos,
I may have fixed the problem. Try v1.6.11
https://github.com/usgs/gems-tools-arcmap/releases/tag/v1.6.11
